title: Return Early, LLC
email: support@returnearly.net
description: >-
  Linux Packages for Return Early Projects
baseurl: ""
url: "https://packages.returnearly.net"
github_username: returnearly

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
